# Generated by Django 5.2.11 on 2026-02-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pet_type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], max_length=10, verbose_name='Tipo')),
                ('other_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar tipo')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('age', models.IntegerField(verbose_name='Edad (años)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('vaccination_status', models.CharField(choices=[('updated', 'Al día'), ('pending', 'Pendiente'), ('none', 'Sin vacunas')], default='updated', max_length=10, verbose_name='Estado de vacunación')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias o condiciones médicas')),
                ('friendly_with_people', models.BooleanField(default=True, verbose_name='Amigable con personas')),
                ('friendly_with_animals', models.BooleanField(default=True, verbose_name='Amigable con otros animales')),
                ('nervous_at_vet', models.BooleanField(default=False, verbose_name='Nervioso en el veterinario')),
                ('special_care', models.BooleanField(default=False, verbose_name='Requiere cuidado especial')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre contacto emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono contacto emergencia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
    ]
