# Generated by Django 5.2.11 on 2026-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10, unique=True, verbose_name='Día')),
                ('is_open', models.BooleanField(default=True, verbose_name='Abierto')),
                ('opening_time', models.TimeField(default='09:00', verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(default='17:00', verbose_name='Hora de cierre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Horario de Clínica',
                'verbose_name_plural': 'Horarios de Clínica',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('duration', models.IntegerField(verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('icon', models.CharField(default='💉', max_length=10, verbose_name='Icono emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('specialty', models.CharField(choices=[('general', 'Medicina General'), ('surgery', 'Cirugía'), ('dental', 'Odontología'), ('dermatology', 'Dermatología'), ('cardiology', 'Cardiología'), ('emergency', 'Emergencias')], max_length=20, verbose_name='Especialidad')),
                ('license_number', models.CharField(max_length=50, verbose_name='Número de cédula')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('years_experience', models.IntegerField(verbose_name='Años de experiencia')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('available_days', models.JSONField(default=list, help_text='Lista de días disponibles', verbose_name='Días disponibles')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Hora de fin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vets/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
                'ordering': ['name'],
            },
        ),
    ]
