# Generated by Django 5.2.11 on 2026-02-26 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_clinicschedule_service_veterinarian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('general', 'Información General'), ('care', 'Cuidado de Mascotas'), ('health', 'Salud y Vacunación'), ('nutrition', 'Nutrición'), ('training', 'Entrenamiento'), ('other', 'Otros')], default='general', max_length=50, verbose_name='Categoría')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo PDF')),
                ('icon', models.CharField(default='📄', max_length=10, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
